version: '3'
services:
  python:
    # image: python:3.4
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=eco_product
      - POSTGRES_PASSWORD=eco_product
      - POSTGRES_DB=eco_product_dev

volumes:
  postgres_data: