# Generated by Django 5.0.1 on 2024-04-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'About Page SEO',
                'verbose_name_plural': 'About Page SEO',
            },
        ),
        migrations.CreateModel(
            name='BlogPageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blog Page SEO',
                'verbose_name_plural': 'Blog Page SEO',
            },
        ),
        migrations.CreateModel(
            name='CompaniesPageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Companies Page SEO',
                'verbose_name_plural': 'Companies Page SEO',
            },
        ),
        migrations.CreateModel(
            name='ContactPageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Page SEO',
                'verbose_name_plural': 'Contact Page SEO',
            },
        ),
        migrations.CreateModel(
            name='HomePageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Home Page SEO',
                'verbose_name_plural': 'Home Page SEO',
            },
        ),
        migrations.CreateModel(
            name='ShopPageSeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('keyword', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Shop Page SEO',
                'verbose_name_plural': 'Shop Page SEO',
            },
        ),
    ]
