# Generated by Django 5.0.1 on 2024-01-22 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_options_categorybanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybanner',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='product.productcategory'),
        ),
    ]
