# Generated by Django 5.0.1 on 2024-01-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='featured')),
            ],
            options={
                'verbose_name': 'Özəllik',
                'verbose_name_plural': 'Özəlliklər',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='about', verbose_name='image(585x666)px'),
        ),
    ]
