# Generated by Django 5.0.1 on 2024-01-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_feature_alter_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='featured'),
        ),
    ]
