# Generated by Django 5.0.1 on 2024-01-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(null=True, upload_to='company', verbose_name='image(379x335)px'),
        ),
    ]
