# Generated by Django 5.0.1 on 2024-01-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_company_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='partners')),
            ],
            options={
                'verbose_name': 'Tərəfdaş',
                'verbose_name_plural': 'Tərəfdaşlar',
            },
        ),
    ]
