# Generated by Django 5.0.1 on 2024-01-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('product', models.BigIntegerField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('brend', models.IntegerField(blank=True, null=True)),
                ('new_taste', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistika',
            },
        ),
    ]
