# Generated by Django 5.0.1 on 2024-01-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_generalsettings_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='adress',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Ünvan'),
        ),
    ]
