# Generated by Django 5.0.1 on 2024-01-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_contact_alter_phonenumber_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
