# Generated by Django 5.0.1 on 2024-01-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_phonenumber_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='product.generalsettings'),
        ),
    ]
