# Generated by Django 5.0.1 on 2024-01-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_phonenumber_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_main_page',
            field=models.BooleanField(default=True),
        ),
    ]
