# Generated by Django 5.0.1 on 2024-01-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_productcategory_is_main_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contact_page')),
            ],
            options={
                'verbose_name': 'Əlaqə səhifəsi',
                'verbose_name_plural': 'Əlaqə səhifəsi',
            },
        ),
    ]
