# Generated by Django 5.0.1 on 2024-01-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
