# Generated by Django 5.0.1 on 2024-02-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_basketitem_options_basket_basketitem_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='basket',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
