# Generated by Django 5.0.1 on 2024-02-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_alter_couponusage_coupon_alter_couponusage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_active',
        ),
    ]
