# Generated by Django 5.0.1 on 2024-02-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
