# Generated by Django 5.0.1 on 2024-02-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_order_discount_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Gözləmədə'), ('Processing', 'İşlənir'), ('Shipped', 'Göndərilib'), ('Delivered', 'Çatdırılıb'), ('Cancelled', 'Ləğv edilib')], default='Pending', max_length=20),
        ),
    ]
