# Generated by Django 5.0.1 on 2024-02-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sifariş', 'verbose_name_plural': 'Sifarişlər'},
        ),
        migrations.AddField(
            model_name='statistic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='statistic'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Gözləmədə', 'Pending'), ('İşlənir', 'Processing'), ('Göndərilib', 'Shipped'), ('Çatdırılıb', 'Delivered'), ('Ləğv edilib', 'Cancelled')], default='Gözləmədə', max_length=20),
        ),
    ]
