# Generated by Django 5.0.1 on 2024-02-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_alter_order_options_statistic_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='statistic', verbose_name='img(610x315)'),
        ),
    ]
