# Generated by Django 5.0.1 on 2024-02-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_alter_statistic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexslider',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='index_slider_mobile'),
        ),
    ]
