# Generated by Django 5.0.1 on 2024-02-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_indexslider_mobile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexslider',
            name='mobile_description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='mobile_title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='indexslider',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='index_slider_mobile', verbose_name='Mobile photo(366x350px)'),
        ),
    ]
