# Generated by Django 5.0.1 on 2024-03-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_indexslider_mobile_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-stock'], 'verbose_name': 'Məhsul', 'verbose_name_plural': 'Məhsullar'},
        ),
        migrations.AddField(
            model_name='order',
            name='tracing_url',
            field=models.URLField(null=True),
        ),
    ]
