# Generated by Django 5.0.1 on 2024-03-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_alter_product_options_order_tracing_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tracing_url',
            new_name='tracking_url',
        ),
        migrations.AddField(
            model_name='order',
            name='order_reference_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
