# Generated by Django 5.0.1 on 2024-03-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_rename_tracing_url_order_tracking_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_reference_id',
            new_name='wolt_order_reference_id',
        ),
    ]
