# Generated by Django 5.0.1 on 2024-03-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_rename_order_reference_id_order_wolt_order_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='wolt_order_reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
