# Generated by Django 5.0.1 on 2024-03-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_alter_order_tracking_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_wolt',
            field=models.BooleanField(default=False),
        ),
    ]
