# Generated by Django 5.0.1 on 2024-03-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_order_is_wolt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Gözləmədə', 'Gözləmədə'), ('İşlənir', 'İşlənir'), ('Göndərilib', 'Göndərilib'), ('Çatdırılıb', 'Çatdırılıb'), ('Ləğv edilib', 'Ləğv edilib')], default='Gözləmədə', max_length=20),
        ),
    ]
