# Generated by Django 5.0.1 on 2024-03-25 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_alter_transaction_payment_redirect_url'),
        ('product', '0053_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='payment.transaction'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Gözləmədə', 'Gözləmədə'), ('Hazırlandı', 'Hazırlandı'), ('Göndərilib', 'Göndərilib'), ('Çatdırılıb', 'Çatdırılıb'), ('Ləğv edilib', 'Ləğv edilib')], default='Gözləmədə', max_length=20),
        ),
    ]
