# Generated by Django 5.0.1 on 2024-03-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_order_transaction_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Gözləmədə', 'Gözləmədə'), ('Hazırlandı', 'Hazırlandı'), ('Göndərilib', 'Göndərilib'), ('Çatdırılıb', 'Çatdırılıb'), ('Ləğv edilib', 'Ləğv edilib')], default='Gözləmədə', max_length=20, null=True),
        ),
    ]
