# Generated by Django 5.0.1 on 2024-03-25 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Gözləmədə', 'Gözləmədə'), ('Hazırlandı', 'Hazırlandı'), ('Göndərilib', 'Göndərilib'), ('Çatdırılıb', 'Çatdırılıb'), ('Ləğv edilib', 'Ləğv edilib')], default='Gözləmədə', max_length=20)),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Təsdiqlənib')),
                ('ordering', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='product.order')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuslar',
                'ordering': ['order', 'ordering'],
            },
        ),
    ]
