# Generated by Django 5.0.1 on 2024-03-25 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('status', 'order')},
        ),
    ]
