# Generated by Django 5.0.1 on 2024-03-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_remove_order_status_alter_status_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False, verbose_name='Ən çox satılan'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_most_wonted',
            field=models.BooleanField(default=False, verbose_name='Ən çox axtarılan'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=False, verbose_name='Trenddə olan'),
        ),
    ]
