# Generated by Django 5.0.1 on 2024-03-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0058_product_is_best_seller_product_is_most_wonted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-stock', '-pk'], 'verbose_name': 'Məhsul', 'verbose_name_plural': 'Məhsullar'},
        ),
        migrations.AddField(
            model_name='product',
            name='sale_count',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Satış sayı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_main_page',
            field=models.BooleanField(default=False, verbose_name='Ana səhifədə görünən'),
        ),
    ]
