# Generated by Django 5.0.1 on 2024-03-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0060_status_select_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='select_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
