# Generated by Django 5.0.1 on 2024-03-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0063_remove_status_select_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='select_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
