# Generated by Django 5.0.1 on 2024-04-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0066_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
