# Generated by Django 5.0.1 on 2024-04-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0068_productcategory_slug_alter_productcategory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
