# Generated by Django 5.0.1 on 2024-04-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
