# Generated by Django 5.0.1 on 2024-04-04 12:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0074_blog_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_az',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='keywords_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='keywords_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='keywords_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_az',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='categorybanner',
            name='title_az',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorybanner',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='categorybanner',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_az',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title1_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title1_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title1_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title2_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title2_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title2_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='adress_az',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='adress_en',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='adress_ru',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='copyright_title_az',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='copyright_title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='copyright_title_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='footer_slogan_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='footer_slogan_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='footer_slogan_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='site_title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Saytın başlığı'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='site_title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Saytın başlığı'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='site_title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Saytın başlığı'),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='description_az',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='description_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='description_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='mobile_description_az',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='mobile_description_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='mobile_description_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='mobile_title_az',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='mobile_title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='mobile_title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='title_az',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='title_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indexslider',
            name='title_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_az',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_az',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
