# Generated by Django 5.0.1 on 2024-04-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0075_about_description_az_about_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='keywords_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='keywords_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='keywords_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_ru',
        ),
    ]
