# Generated by Django 5.0.1 on 2024-04-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_product_description_az_product_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='adress_az',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='adress_en',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='adress_ru',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='copyright_title_az',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='copyright_title_en',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='copyright_title_ru',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='footer_slogan_az',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='footer_slogan_en',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='footer_slogan_ru',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='site_title_az',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='site_title_en',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='site_title_ru',
        ),
    ]
