# Generated by Django 5.0.1 on 2024-04-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0078_remove_generalsettings_adress_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='adress_az',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='adress_en',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='adress_ru',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Ünvan'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='copyright_title_az',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='copyright_title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='copyright_title_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='footer_slogan_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='footer_slogan_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='footer_slogan_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='site_title_az',
            field=models.CharField(max_length=200, null=True, verbose_name='Saytın başlığı'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='site_title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Saytın başlığı'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='site_title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Saytın başlığı'),
        ),
    ]
