# Generated by Django 4.2.11 on 2024-05-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0079_generalsettings_adress_az_generalsettings_adress_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='work_finish_hour',
            field=models.TimeField(null=True, verbose_name='İşin bitmə saatı'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='work_start_hour',
            field=models.TimeField(null=True, verbose_name='İşin başlama saatı'),
        ),
    ]
