# Generated by Django 4.2.11 on 2024-07-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0080_generalsettings_work_finish_hour_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pk'], 'verbose_name': 'Bloglar', 'verbose_name_plural': 'Bloglar'},
        ),
    ]
