# Generated by Django 4.2.11 on 2024-07-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0081_alter_blog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Order status',
                'verbose_name_plural': 'Order statusları',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Yeni', 'Yeni'), ('Paketlənən', 'Paketlənən'), ('Təhvilə hazır', 'Təhvilə hazır'), ('Tammalanmış', 'Tamamlanmış')], default='Yeni', max_length=20),
        ),
    ]
