# Generated by Django 4.2.11 on 2024-07-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0082_ordertype_order_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderType',
        ),
    ]
