# Generated by Django 4.2.11 on 2024-07-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0083_delete_ordertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Yeni', 'Yeni'), ('Paketlənən', 'Paketlənən'), ('Təhvilə hazır', 'Təhvilə hazır'), ('Tammalanmış', 'Tamamlanmış')], default='Yeni', max_length=20, verbose_name='Sifariş növü'),
        ),
    ]
