# Generated by Django 4.2.11 on 2024-07-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0084_remove_order_type_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_code',
            field=models.BigIntegerField(default=0, verbose_name='Məhsulun barkodu'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Məhsulun kodu'),
        ),
    ]
