# Generated by Django 4.2.11 on 2024-07-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0087_alter_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Yeni', 'Yeni'), ('Paketlənən', 'Paketlənən'), ('Təhvilə hazır', 'Təhvilə hazır'), ('Tammalanmış', 'Tamamlanmış')], default='Yeni', max_length=20, verbose_name='Sifariş növü'),
        ),
    ]
