# Generated by Django 4.2.11 on 2024-07-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0090_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='box_choice',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Qutu seçimi'),
        ),
    ]
