# Generated by Django 4.2.11 on 2024-07-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0091_orderitem_box_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='box_choice',
            field=models.CharField(blank=True, choices=[('kiçik', 'kiçik'), ('orta', 'orta'), ('böyük', 'böyük')], max_length=20, null=True, verbose_name='Qutu seçimi'),
        ),
    ]
