# Generated by Django 4.2.11 on 2024-08-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
    ]
