# Generated by Django 4.2.11 on 2024-08-29 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_remove_apikey_supporter_name_apikey_supporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('url', 'ip_address', 'date')},
            },
        ),
    ]
