# Generated by Django 4.2.11 on 2024-08-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_alter_pageview_unique_together_pageview_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_pattern', models.CharField(help_text='Regex pattern for URLs to monitor', max_length=255, unique=True)),
                ('is_monitored', models.BooleanField(default=True, help_text='Whether this URL should be monitored for visits')),
            ],
        ),
    ]
