# Generated by Django 4.2.11 on 2024-08-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_monitoredurl'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pageview',
            name='config_page_url_002983_idx',
        ),
        migrations.AlterField(
            model_name='pageview',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='pageview',
            unique_together={('url', 'ip_address', 'timestamp')},
        ),
    ]
