# Generated by Django 4.2.11 on 2024-08-29 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0011_remove_pageview_config_page_url_002983_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pageview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pageview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pageview',
            unique_together={('url', 'ip_address', 'timestamp', 'user')},
        ),
    ]
