# Generated by Django 4.2.11 on 2024-09-02 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_alter_pageview_unique_together_pageview_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('is_workday', models.BooleanField(default=True)),
                ('work_start_hour', models.TimeField(default=datetime.time(9, 0))),
                ('work_finish_hour', models.TimeField(default=datetime.time(17, 0))),
            ],
        ),
    ]
