# Generated by Django 4.2.11 on 2024-09-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='work_finish_hour',
        ),
        migrations.RemoveField(
            model_name='generalsettings',
            name='work_start_hour',
        ),
    ]
