# Generated by Django 4.2.11 on 2024-08-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_transaction_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='delivery_amount',
        ),
    ]
