# Generated by Django 4.2.11 on 2024-08-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_amount_transaction_delivery_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='delivery_amount',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
