# Generated by Django 4.2.11 on 2024-08-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='setting',
        ),
        migrations.DeleteModel(
            name='GeneralSettings',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
