# Generated by Django 4.2.11 on 2024-08-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_phonenumber_setting_delete_generalsettings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
