# Generated by Django 4.2.11 on 2024-08-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_delete_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorybanner',
            name='category',
        ),
        migrations.DeleteModel(
            name='IndexSlider',
        ),
        migrations.DeleteModel(
            name='CategoryBanner',
        ),
    ]
