# Generated by Django 4.2.11 on 2024-08-05 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_apikey_is_test'),
        ('product', '0004_remove_categorybanner_category_delete_indexslider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='config.apikey'),
        ),
    ]
