# Generated by Django 4.2.11 on 2024-08-05 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_remove_apikey_customer_name_apikey_supporter_name'),
        ('product', '0005_product_created_by_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by_customer',
        ),
        migrations.AddField(
            model_name='product',
            name='created_by_supporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='config.apikey', verbose_name='Dəstəkçi'),
        ),
    ]
