# Generated by Django 4.2.11 on 2024-08-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_created_product_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Supporter (Məsələn: logix) tərəfindan yaradıldığı zaman təsdiqlənmədən aktiv olmasına icazə verilmir.', verbose_name='Saytda görünən və ya aktiv olan'),
        ),
    ]
