# Generated by Django 4.2.11 on 2024-08-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_test',
            field=models.BooleanField(default=True, verbose_name='Test üçün (Saytda görünmür)'),
        ),
    ]
