# Generated by Django 4.2.11 on 2024-08-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_is_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='Test üçün (Saytda görünmür)'),
        ),
    ]
