# Generated by Django 4.2.11 on 2024-08-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_created_by_supporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by_supporter',
        ),
    ]
