# Generated by Django 4.2.11 on 2024-08-05 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('product', '0016_remove_product_created_by_supporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by_supporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.supporter', verbose_name='Dəstəkçi'),
        ),
    ]
