# Generated by Django 4.2.11 on 2024-08-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_created_by_supporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
