# Generated by Django 4.2.11 on 2024-08-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_order_delivery_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivery_free',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
