# Generated by Django 4.2.11 on 2024-08-29 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('product', '0019_order_is_delivery_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='created_by_supporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_categories', to='core.supporter', verbose_name='Dəstəkçi'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Supporter (Məsələn: logix) tərəfindan yaradıldığı zaman təsdiqlənmədən aktiv olmasına icazə verilmir.', verbose_name='Saytda görünən və ya aktiv olan'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='Test üçün (Saytda görünmür)'),
        ),
    ]
