# Generated by Django 4.2.11 on 2024-08-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_productcategory_created_productcategory_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
