# Generated by Django 4.2.11 on 2024-09-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_product_click_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
