# Generated by Django 4.2.11 on 2024-11-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_product_title_alter_product_title_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='logix_product_id',
            field=models.PositiveBigIntegerField(null=True, unique=True),
        ),
    ]
