# Generated by Django 4.2.11 on 2024-11-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_product_logix_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='logix_product_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
