# Generated by Django 4.2.11 on 2024-11-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_productcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='logix_product_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
