# Generated by Django 5.0.1 on 2024-02-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='LoginRegisterPage',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
