# Generated by Django 5.0.1 on 2024-03-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0002_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wolt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
