# Generated by Django 5.0.1 on 2024-03-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
