# Generated by Django 5.0.1 on 2024-03-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_transaction_amount_transaction_lat_transaction_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_wolt',
            field=models.BooleanField(default=False),
        ),
    ]
