# Generated by Django 5.0.1 on 2024-03-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_transaction_is_wolt'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
