# Generated by Django 5.0.1 on 2024-03-18 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_transaction_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_checked_from_eco',
            field=models.BooleanField(default=False),
        ),
    ]
