# Generated by Django 5.0.1 on 2024-03-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_transaction_delivery_redirect_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='delivery_redirect_url',
            new_name='payment_redirect_url',
        ),
    ]
