# Generated by Django 5.0.1 on 2024-03-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_rename_delivery_redirect_url_transaction_payment_redirect_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
