# Generated by Django 5.0.1 on 2024-03-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_alter_transaction_payment_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='dropoff_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
