# Generated by Django 4.2.11 on 2024-07-01 20:55

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200, verbose_name='Şöbənin adı')),
            ],
            options={
                'verbose_name': 'Şöbə',
                'verbose_name_plural': 'Şöbələr',
            },
        ),
        migrations.CreateModel(
            name='IPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_ip', models.GenericIPAddressField(editable=False, verbose_name='IP ünvanı')),
            ],
            options={
                'verbose_name': 'IP ünvanı',
                'verbose_name_plural': 'IP ünvanları',
            },
        ),
        migrations.CreateModel(
            name='JobLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_level', models.CharField(max_length=200, verbose_name='Vəzifə dərəcəsi')),
            ],
            options={
                'verbose_name': 'Vəzifə dərəcəsi',
                'verbose_name_plural': 'Vəzifə dərəcələri',
            },
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=200, verbose_name='Məşğulluğun növü')),
            ],
            options={
                'verbose_name': 'Məşğulluq növü',
                'verbose_name_plural': 'Məşğulluq növləri',
            },
        ),
        migrations.CreateModel(
            name='VacancyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_type', models.CharField(max_length=200, verbose_name='Elanın növü')),
            ],
            options={
                'verbose_name': 'Elanın növü',
                'verbose_name_plural': 'Elanın növləri',
            },
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.TimeField(default=datetime.datetime(2024, 7, 1, 20, 55, 20, 117698, tzinfo=datetime.timezone.utc), verbose_name='İşin başlama saatı')),
                ('end_date', models.TimeField(default=datetime.datetime(2024, 7, 1, 20, 55, 20, 118345, tzinfo=datetime.timezone.utc), verbose_name='İşin bitmə saatı')),
            ],
            options={
                'verbose_name': 'İş qrafiki',
                'verbose_name_plural': 'İş qrafikləri',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vakansiyanın əlavə edilmə tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('published_at', models.DateTimeField(default=datetime.datetime(2024, 7, 1, 20, 55, 20, 113026, tzinfo=datetime.timezone.utc), verbose_name='Yayımlanma tarixi')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='PB', max_length=2)),
                ('vacancy_title', models.CharField(max_length=200, verbose_name='Vakansiyanın adı')),
                ('vacancy_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Vakansiyanın təsviri')),
                ('salary', models.IntegerField(default=345, verbose_name='Əmək haqqı')),
                ('deadline', models.DateTimeField(default=datetime.datetime(2024, 7, 1, 20, 55, 20, 121345, tzinfo=datetime.timezone.utc), verbose_name='Son müraciət tarixi')),
                ('slug', models.SlugField(blank=True, help_text='Bu qismi boş buraxın. Avtomatik doldurulacaq.', max_length=500, null=True, verbose_name='Link adı')),
                ('department', models.ManyToManyField(blank=True, null=True, related_name='vacancies', to='vacancies.companydepartment', verbose_name='Şöbə')),
                ('job_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.joblevel', verbose_name='Vəzifə dərəcəsi')),
                ('job_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.jobtype', verbose_name='Məşğulluq növü')),
                ('vacancy_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.vacancytype', verbose_name='Elanın növü')),
                ('viewed_ips', models.ManyToManyField(editable=False, related_name='vacancies', to='vacancies.ips', verbose_name='Elanın görüntüləndiyi IP ünvanları')),
                ('work_hour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.workinghour', verbose_name='İş qrafiki')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ('-published_at', '-updated_at'),
                'indexes': [models.Index(fields=['-published_at', '-updated_at'], name='vacancies_v_publish_7a6608_idx')],
            },
        ),
    ]
