# Generated by Django 4.2.11 on 2024-07-02 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='job_level',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 10, 19, 24, 371556, tzinfo=datetime.timezone.utc), verbose_name='Son müraciət tarixi'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 10, 19, 24, 362287, tzinfo=datetime.timezone.utc), verbose_name='Yayımlanma tarixi'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='end_date',
            field=models.TimeField(default=datetime.datetime(2024, 7, 2, 10, 19, 24, 365742, tzinfo=datetime.timezone.utc), verbose_name='İşin bitmə saatı'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='start_date',
            field=models.TimeField(default=datetime.datetime(2024, 7, 2, 10, 19, 24, 365742, tzinfo=datetime.timezone.utc), verbose_name='İşin başlama saatı'),
        ),
        migrations.DeleteModel(
            name='JobLevel',
        ),
    ]
