# Generated by Django 4.2.11 on 2024-07-07 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Son müraciət tarixi'),
        ),
    ]
