# Generated by Django 4.2.11 on 2024-07-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(auto_now_add=True, verbose_name='Son müraciət tarixi'),
        ),
    ]
