# Generated by Django 4.2.11 on 2024-07-02 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_remove_vacancy_job_level_alter_vacancy_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 10, 51, 24, 587151, tzinfo=datetime.timezone.utc), verbose_name='Son müraciət tarixi'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 10, 51, 24, 586148, tzinfo=datetime.timezone.utc), verbose_name='Yayımlanma tarixi'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_title',
            field=models.CharField(max_length=200, verbose_name='Vakant yerin adı'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='end_date',
            field=models.TimeField(default=datetime.datetime(2024, 7, 2, 10, 51, 24, 587151, tzinfo=datetime.timezone.utc), verbose_name='İşin bitmə saatı'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='start_date',
            field=models.TimeField(default=datetime.datetime(2024, 7, 2, 10, 51, 24, 587151, tzinfo=datetime.timezone.utc), verbose_name='İşin başlama saatı'),
        ),
    ]
