# Generated by Django 4.2.11 on 2024-07-07 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_vacancy_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Son müraciət tarixi'),
        ),
    ]
