# Generated by Django 4.2.11 on 2024-07-02 12:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_vacancy_deadline_alter_vacancy_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 12, 25, 24, 33546, tzinfo=datetime.timezone.utc), verbose_name='Son müraciət tarixi'),
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='department',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 12, 25, 24, 27491, tzinfo=datetime.timezone.utc), verbose_name='Yayımlanma tarixi'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='end_date',
            field=models.TimeField(default=datetime.datetime(2024, 7, 2, 12, 25, 24, 31818, tzinfo=datetime.timezone.utc), verbose_name='İşin bitmə saatı'),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='start_date',
            field=models.TimeField(default=datetime.datetime(2024, 7, 2, 12, 25, 24, 31664, tzinfo=datetime.timezone.utc), verbose_name='İşin başlama saatı'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.companydepartment', verbose_name='Şöbə'),
        ),
    ]
