# Generated by Django 4.2.11 on 2024-07-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_vacancy_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancyapplication',
            name='coverletter_az',
        ),
        migrations.RemoveField(
            model_name='vacancyapplication',
            name='coverletter_en',
        ),
        migrations.RemoveField(
            model_name='vacancyapplication',
            name='coverletter_ru',
        ),
    ]
