# Generated by Django 4.2.11 on 2024-07-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_remove_vacancyapplication_coverletter_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyapplication',
            name='coverletter',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Motivasiya məktubu'),
        ),
    ]
