# Generated by Django 4.2.11 on 2024-07-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0016_alter_vacancyapplication_coverletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyapplication',
            name='coverletter',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Motivasiya məktubu'),
        ),
    ]
