# Generated by Django 4.2.11 on 2024-07-14 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0019_alter_vacancyapplication_coverletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='job_type',
        ),
        migrations.DeleteModel(
            name='JobType',
        ),
    ]
