# Generated by Django 4.2.11 on 2024-08-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_remove_categorybanner_category_delete_indexslider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_az', models.CharField(max_length=500, null=True)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('title_ru', models.CharField(max_length=500, null=True)),
                ('mobile_title', models.CharField(max_length=500, null=True)),
                ('mobile_title_az', models.CharField(max_length=500, null=True)),
                ('mobile_title_en', models.CharField(max_length=500, null=True)),
                ('mobile_title_ru', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=500)),
                ('description_az', models.CharField(max_length=500, null=True)),
                ('description_en', models.CharField(max_length=500, null=True)),
                ('description_ru', models.CharField(max_length=500, null=True)),
                ('mobile_description', models.CharField(max_length=500, null=True)),
                ('mobile_description_az', models.CharField(max_length=500, null=True)),
                ('mobile_description_en', models.CharField(max_length=500, null=True)),
                ('mobile_description_ru', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(upload_to='index_slider')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='index_slider_mobile', verbose_name='Mobile photo(366x350px)')),
            ],
            options={
                'verbose_name': 'Slayder',
                'verbose_name_plural': 'Ana səhifə | Slayder',
            },
        ),
        migrations.CreateModel(
            name='CategoryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_az', models.CharField(max_length=500, null=True)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('title_ru', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(upload_to='category_banner')),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='product.productcategory')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Ana səhifə | Seçilmiş Kategoriyalar | Banner',
            },
        ),
    ]
