# Generated by Django 4.2.11 on 2024-08-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorybanner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Seçilmiş Kategoriyalar | Banner'},
        ),
        migrations.AlterModelOptions(
            name='indexslider',
            options={'verbose_name': 'Slayder', 'verbose_name_plural': 'Slayder'},
        ),
    ]
