# Generated by Django 4.2.11 on 2024-08-01 08:33

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200, unique=True, verbose_name='Şöbənin adı')),
                ('department_name_az', models.CharField(max_length=200, null=True, unique=True, verbose_name='Şöbənin adı')),
                ('department_name_en', models.CharField(max_length=200, null=True, unique=True, verbose_name='Şöbənin adı')),
                ('department_name_ru', models.CharField(max_length=200, null=True, unique=True, verbose_name='Şöbənin adı')),
                ('slug', models.SlugField(blank=True, help_text='Bu qismi boş buraxın. Avtomatik doldurulacaq.', max_length=500, null=True, verbose_name='Link adı')),
            ],
            options={
                'verbose_name': 'Şöbə',
                'verbose_name_plural': 'Şöbələr',
            },
        ),
        migrations.CreateModel(
            name='IPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_ip', models.GenericIPAddressField(editable=False, verbose_name='IP ünvanı')),
            ],
            options={
                'verbose_name': 'IP ünvanı',
                'verbose_name_plural': 'IP ünvanları',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vakansiyanın əlavə edilmə tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Yayımlanma tarixi')),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='PB', max_length=2)),
                ('vacancy_title', models.CharField(max_length=200, verbose_name='Vakant yerin adı')),
                ('vacancy_title_az', models.CharField(max_length=200, null=True, verbose_name='Vakant yerin adı')),
                ('vacancy_title_en', models.CharField(max_length=200, null=True, verbose_name='Vakant yerin adı')),
                ('vacancy_title_ru', models.CharField(max_length=200, null=True, verbose_name='Vakant yerin adı')),
                ('vacancy_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Vakansiyanın təsviri')),
                ('vacancy_content_az', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Vakansiyanın təsviri')),
                ('vacancy_content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Vakansiyanın təsviri')),
                ('vacancy_content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Vakansiyanın təsviri')),
                ('salary', models.IntegerField(default='345', help_text='Məbləği manatla daxil edin.', verbose_name='Əmək haqqı')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Son müraciət tarixi')),
                ('slug', models.SlugField(blank=True, help_text='Bu qismi boş buraxın. Avtomatik doldurulacaq.', max_length=500, null=True, verbose_name='Link adı')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.companydepartment', verbose_name='Şöbə')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ('-published_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='VacancyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_type', models.CharField(max_length=200, unique=True, verbose_name='Elanın növü')),
                ('vacancy_type_az', models.CharField(max_length=200, null=True, unique=True, verbose_name='Elanın növü')),
                ('vacancy_type_en', models.CharField(max_length=200, null=True, unique=True, verbose_name='Elanın növü')),
                ('vacancy_type_ru', models.CharField(max_length=200, null=True, unique=True, verbose_name='Elanın növü')),
                ('slug', models.SlugField(blank=True, help_text='Bu qismi boş buraxın. Avtomatik doldurulacaq.', max_length=500, null=True, verbose_name='Link adı')),
            ],
            options={
                'verbose_name': 'Elanın növü',
                'verbose_name_plural': 'Elanın növləri',
            },
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_hour', models.CharField(max_length=200, unique=True, verbose_name='İş qrafiki')),
                ('work_hour_az', models.CharField(max_length=200, null=True, unique=True, verbose_name='İş qrafiki')),
                ('work_hour_en', models.CharField(max_length=200, null=True, unique=True, verbose_name='İş qrafiki')),
                ('work_hour_ru', models.CharField(max_length=200, null=True, unique=True, verbose_name='İş qrafiki')),
                ('slug', models.SlugField(blank=True, help_text='Bu qismi boş buraxın. Avtomatik doldurulacaq.', max_length=500, null=True, verbose_name='Link adı')),
            ],
            options={
                'verbose_name': 'İş qrafiki',
                'verbose_name_plural': 'İş qrafikləri',
            },
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Müraciətin edilmə tarixi')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad, soyad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email ünvanı')),
                ('CV', models.FileField(upload_to='vacancy-applications', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])])),
                ('coverletter', models.TextField(blank=True, null=True, verbose_name='Motivasiya məktubu')),
                ('prtfolio_website', models.URLField(blank=True, null=True, verbose_name='Portfolio')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancies.vacancy', verbose_name='Elan')),
            ],
            options={
                'verbose_name': 'Müraciət',
                'verbose_name_plural': 'Müraciətlər',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.vacancytype', verbose_name='Elanın növü'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='viewed_ips',
            field=models.ManyToManyField(editable=False, related_name='vacancies', to='vacancies.ips', verbose_name='Elanın görüntüləndiyi IP ünvanları'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_hour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancies.workinghour', verbose_name='İş qrafiki'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['-published_at', '-updated_at'], name='vacancies_v_publish_7a6608_idx'),
        ),
    ]
