# Generated by Django 4.2.11 on 2024-09-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0002_faq_faqcategory_delete_supporter_faq_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_az',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.TextField(null=True),
        ),
    ]
