# Generated by Django 4.2.11 on 2024-09-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0003_alter_faq_question_alter_faq_question_az_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
    ]
